skip_welcome_message = true

[line_editor]
edit_mode = "nvim"

startup = [
    "alias el = exa -la",
    "alias .sw = lf ~/.config/sway/config.d",
    "alias .a = nvim ~/.config/alacrittty/alacritty.yml",
    "alias v = nvim",
    "alias sv = sudo nvim",
    "alias pac = pacman -Slq | sk --multi --preview 'pacman -Si {1}' | xargs -ro sudo pacman -S",
    #"alias aur = paru -Sl | awk '{print \$2(\$4==\'\' ? \'\' : \' *\')}' | sk --multi --preview 'paru -Si {1}' | cut -d \' \' -f 1 | xargs -ro paru -S",
    "alias pr = pacman -Qq | sk --multi --preview 'pacman -Qi {1}' | xargs -ro sudo pacman -Rns",
    "def nudown [] {fetch https://api.github.com/repos/nushell/nushell/releases | get assets | select name download_count}",
    "def nuver [] {version | pivot key value}",
    ]
